<a href="https://colab.research.google.com/github/klnsuman/ALGO-DS-PYTHON/blob/master/Python_Interview.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%timeit L = [n ** 2 for n in range(1000)]

1000 loops, best of 3: 257 µs per loop


In [2]:
%%timeit
L = []
for n in range(1000):
  L.append(n**2)

1000 loops, best of 3: 293 µs per loop


In [4]:
import math

math.sin(90)

0.8939966636005579

In [5]:
print(In)

['', "get_ipython().magic('timeit L = [n ** 2 for n in range(1000)]')", "get_ipython().run_cell_magic('timeit', '', 'L = []\\nfor n in range(1000):\\n  L.append(n**2)')", 'import math\n\nmath.sin(2)', 'import math\n\nmath.sin(90)', 'print(In)']


In [9]:
math.cos(45)

0.5253219888177297

In [10]:
def func1(a,b):
  return a/b
  

In [11]:
def func2(x):
  a = x
  b = x - 1
  return func1(a,b)

In [12]:
func2(1)

ZeroDivisionError: ignored

In [13]:
%xmode Plain

Exception reporting mode: Plain


In [14]:
func2(1)

ZeroDivisionError: ignored

In [15]:
%xmode Verbose
func2(1)

Exception reporting mode: Verbose


ZeroDivisionError: ignored

In [16]:
%debug

> <ipython-input-10-cbdd939ae55d>(2)func1()
      1 def func1(a,b):
----> 2   return a/b
      3 

ipdb> 
ipdb> 
ipdb> 1
1
ipdb> 0
0
ipdb> quit


In [19]:
import random
L = [random.random() for i in range(10)]
L

[0.4451350901881178,
 0.6557399636639017,
 0.3944643815745964,
 0.8041013528726124,
 0.4173549545880063,
 0.23603397867428022,
 0.6176186941295608,
 0.8571309480034491,
 0.2709945676054438,
 0.08937404630359891]

In [20]:
import numpy
numpy.__version__

'1.18.5'

In [24]:
L = list(range(10))
L
type(L[0])

int

In [30]:
L1 = list((str(c),c) for c in L)
type(L1[0])

tuple

In [31]:
import array
L = list(range(10))
A = array.array('i',L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## **1. Numpy**

In [33]:
import numpy as np

  ## 1.1 Create Zero Array

In [41]:
#a = np.zeros(10,dtype=int)
a = np.zeros((2,2),dtype=int)
a

array([[0, 0],
       [0, 0]])

## 1.2 Create Random Array

In [42]:
#b = np.random.random(10)
b = np.random.random((3,3))
b

array([[0.43441345, 0.9054934 , 0.59358285],
       [0.53545836, 0.5684055 , 0.44429147],
       [0.65438871, 0.9485399 , 0.23843762]])

In [44]:
c = np.random.randint((3,3))
c

array([0, 2])